name: Test my hw3

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Test 'minimum_of_nums'
        run: python -m unittest tests.Tests.test_minimum

      - name: Test 'maximum_of_nums'
        run: python -m unittest tests.Tests.test_maximum

      - name: Test 'sum_of_nums'
        run: python -m unittest tests.Tests.test_sum

      - name: Test 'multiplication_of_nums'
        run: python -m unittest tests.Tests.test_multiplication
