name: Test my project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Run 'minimum_of_nums'
        run: python unittest tests.py
