name: Test my hw3

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Test hw3
        run: python -m unittest --verbose tests
