name: Test my project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'minimum_of_nums'
        run: python -m unittest tests.Tests.test_minimum
